---
- name: Create a new CI
  uri:
    url: https://{{ instance_url }}/api/now/table/cmdb_ci_linux_server
    method: POST
    user: "{{ instance_username }}"
    password: "{{ instance_password }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    body: >
      {
        "virtual": "true",
        "name": "test_from_ansible",
        "os": "Linux",
        "cpu_count": "1",
        "vendor": "Generic"
      }
  register: restreturn

- debug:
    var: restdata.json.results